#!/usr/bin/env bash
#
#  install-nanoconfig
#
#  Copyright (c) 2016, 2018 Stephen Whittle  All rights reserved.
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"),
#  to deal in the Software without restriction, including without limitation
#  the rights to use, copy, modify, merge, publish, distribute, sublicense,
#  and/or sell copies of the Software, and to permit persons to whom
#  the Software is furnished to do so, subject to the following conditions:
#  The above copyright notice and this permission notice shall be included
#  in all copies or substantial portions of the Software.
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
#  THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
#  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
#  IN THE SOFTWARE.

if [[ $(id -u) -ne 0 ]] ; then
    printf "must be a superuser!!!\n" >&2

    exit 1
fi

package="nanoconfig"
install_dir="/usr/local/src"

apt-get update
rc=$?

[[ $rc -ne 0 ]] && exit $rc

apt-get install -y git \
                   build-essential \
                   cmake
rc=$?

[[ $rc -ne 0 ]] && exit $rc

if [[ ! -d "$install_dir" ]] ; then
    mkdir --parents \
          "$install_dir"
    rc=$?

    [[ $rc -ne 0 ]] && exit $rc
fi

cd "$install_dir"
rc=$?

[[ $rc -ne 0 ]] && exit $rc

if [[ ! -d "$package" ]] ; then
    git clone "https://github.com/nanomsg/$package.git"
    rc=$?

    [[ $rc -ne 0 ]] && exit $rc
fi

cd "$package"
rc=$?

[[ $rc -ne 0 ]] && exit $rc

prefix_install="/usr/local"

cmake .
rc=$?

[[ $rc -ne 0 ]] && exit $rc
make
rc=$?

[[ $rc -ne 0 ]] && exit $rc
make install
rc=$?

[[ $rc -ne 0 ]] && exit $rc

pc_file="$prefix_install/lib/pkgconfig/$package.pc"

if [[ ! -f "$pc_file" ]] ; then
    (
        printf "prefix=%s\n" "$prefix_install"
        printf "exec_prefix=\${prefix}\n"
        printf "includedir=\${prefix}/include\n"
        printf "libdir=\${prefix}/lib\n"
        printf "\n"
        printf "Name: %s\n" "$package"
        printf "Description: The configuration service for nanomsg\n"
        printf "URL: https://github.com/nanomsg/%s\n" "$package"
        printf "Version: 0.0.1\n"
        printf "Requires: nanomsg\n"
        printf "Libs: -L\${libdir} -l%s\n" "$package"
        printf "Libs.private: -lanl -lrt -lpthread -lnsl\n"
        printf "Cflags: -I\${includedir}\n"
    ) >"$pc_file"
fi

[[ $rc -ne 0 ]] && exit $rc

ldconfig "$prefix_install/lib"
rc=$?

[[ $rc -ne 0 ]] && exit $rc

exit 0
